[package]
name = "rust_snake"
version = "0.1.0"
authors = ["thanadolps <thanadolps@gmail.com>"]
edition = "2018"

[dependencies]
ndarray = "0.12.1"
ndarray-parallel = "0.9.0"
num-traits = "0.2.8"
console = "0.7.7"
rand = "0.7.0"
text_io = "0.1.7"
readonly = "0.1.4"