[package]
name = "rust_snake"
version = "0.1.0"
authors = ["thanadolps <thanadolps@gmail.com>"]
edition = "2018"

[dependencies]
ndarray = "0.12"
ndarray-parallel = "0.9"
num-traits = "0.2"
rand = "0.7"
readonly = "0.1"

[dev-dependencies]
console = "0.7"
text_io = "0.1"
